'use client';

interface LiveReportProps {
  content: string;
  isLoading: boolean;
  language: 'no' | 'en';
  onRefresh: () => void;
}

export function LiveReport({ content, isLoading, language, onRefresh }: LiveReportProps) {
  const t = {
    no: {
      title: 'Live Markedsrapport',
      subtitle: 'Generert av Apex Quantum AI',
      refresh: 'Oppdater',
      loading: 'Analyserer markeder...',
      lastUpdate: 'Oppdateres automatisk hvert 10. minutt',
    },
    en: {
      title: 'Live Market Report',
      subtitle: 'Generated by Apex Quantum AI',
      refresh: 'Refresh',
      loading: 'Analyzing markets...',
      lastUpdate: 'Auto-updates every 10 minutes',
    },
  }[language];

  return (
    <section className="py-16 px-6">
      <div className="max-w-5xl mx-auto">
        <div className="bg-card border border-border rounded-3xl overflow-hidden">
          <div className="flex items-center justify-between px-6 py-4 border-b border-border">
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-accent pulse-live" />
                <span className="font-semibold">{t.title}</span>
              </div>
              <span className="text-sm text-muted-foreground hidden sm:block">{t.subtitle}</span>
            </div>
            <button
              onClick={onRefresh}
              disabled={isLoading}
              className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors disabled:opacity-50"
            >
              <svg
                viewBox="0 0 24 24"
                fill="none"
                className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`}
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8" />
                <path d="M21 3v5h-5" />
              </svg>
              {t.refresh}
            </button>
          </div>

          <div className="p-6 md:p-8 min-h-[50vh]">
            {isLoading ? (
              <div className="flex flex-col items-center justify-center h-[40vh] gap-4">
                <div className="w-10 h-10 border-2 border-accent border-t-transparent rounded-full animate-spin" />
                <p className="text-muted-foreground">{t.loading}</p>
              </div>
            ) : content ? (
              <div className="prose-custom font-mono text-sm whitespace-pre-wrap">{content}</div>
            ) : null}
          </div>

          <div className="px-6 py-4 border-t border-border">
            <p className="text-xs text-muted-foreground text-center">{t.lastUpdate}</p>
          </div>
        </div>
      </div>
    </section>
  );
}
